# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PHP Indonesia Chapter Jakarta
email: phpid.jakarta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Komunitas PHP Indonesia Regional Jakarta
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jakarta.phpindonesia.or.id"
enforce_ssl: jakarta.phpindonesia.or.id


excerpt_separator: <a name='more'></a>
paginate: 5
twitter_username: phpid-jakarta
github_username:  phpid-jakarta
facebook_url: https://facebook.com/profile.php?id=100011420743645
disqus:
   shortname: phpid-jakarta
google_analytics: UA-97096911-1
copyright_year: 2017

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock

# SASS setup  
sass:
  sass_dir: _sass
  style: compressed

# autoprefixer
autoprefixer:
  only_production: true
  browsers:
  - last 2 versions  
